# Generated by Django 5.1.6 on 2025-02-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "add_task_status_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskassignment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
