# Generated by Django 5.1.6 on 2025-02-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("overdue", "Overdue"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
