# Generated by Django 5.1.6 on 2025-02-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0001_alter_taskassignment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                    ("completed", "Completed"),
                    ("revision", "Revision"),
                    ("overdue", "Overdue"),
                ],
                default="assigned",
                max_length=20,
            ),
        ),
    ]
