# Generated by Django 5.1.6 on 2025-02-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0003_taskcompletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[("photo", "Photo"), ("video", "Video")],
                max_length=10,
                null=True,
            ),
        ),
    ]
