# Generated by Django 5.1.6 on 2025-02-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0004_task_media_type"),
        ("robot", "add_multi_task_support"),
    ]

    operations = []
