# Generated by Django 5.1.6 on 2025-02-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("robot", "0005_merge_0004_task_media_type_add_multi_task_support"),
        ("robot", "add_task_acceptance"),
    ]

    operations = []
